dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  http: ^1.2.2
  mobx: ^2.3.3+2
  flutter_mobx: ^2.2.1+1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  mobx_codegen: ^2.6.1
  build_runner: ^2.4.11

flutter:

  assets:
    - assets/images/

  fonts:
    - family: Google
      fonts:
        - asset: assets/fonts/ProductSans-Bold.ttf
        - asset: assets/fonts/ProductSans-Regular.ttf
          weight: 700